Optimize cut point selection
hlin117/mdlp-discretization pull request #28
Opened 2017-11-12 07:30 UTC by dodgejoel

This should address #27.

The approach that I took was to be slightly more careful about which cut points should be considered. A cut point is skipped over if:
1. it does not correspond to a change in col-value, or 
2. the labels for the previous col-value and the labels for the current col-value are identical and consist of exactly one label.

2. is a reasonable condition to use here because it is precisely this configuration of label values which ensures that the cut point in question is *not* a so-called boundary point (in the language of the original paper).

Making these changes to the logic in find_cut_points necessitated injecting some auxiliary data into the function.

In addition, I have refactored how the iris test result data to make them easier to update and reuse. Now they stored in a csv instead of inlined in python. I have also included some testing util functions for loading and updating these data.

2017-11-12 20:28 UTC, hlin117 reviewed
A couple of issues with this PR:

1. You shouldn't use a dict in Cython
2. Your test case still uses the Iris dataset, so you're finding the need to import test fixtures
3. You're introducing breaking changes for those who have the package already. My suggestion is to pass a parameter in indicating whether they would like to use this optimization criterion. 

I'm also convinced that there's an easier way to do this, but I need to think about this problem more closely.

2017-11-12 20:28 UTC, hlin117 commented on mdlp/_mdlp.pyx
> +    labels_map: dict
I highly recommend you do not use a python `dict` in Cython code. One of the biggest reasons we code in Cython is so we can avoid the python GIL on critical code paths. So by using a `dict`, you're actually defeating the purpose of entering Cython land.

See https://stackoverflow.com/a/32267243/2014591.

2017-11-12 20:28 UTC, hlin117 commented on tests/test_mdlp.py
>  def test_mdlp_iris():
To be honest, I never liked this test in the first place. When I wrote this code, I wasn't aware of good testing practices. If I were to rewrite this code again, I would use a much smaller dataset to test with (maybe a `4 x 2` array?)

2017-11-12 20:28 UTC, hlin117 commented on mdlp/_mdlp.pyx
>      If k split the array into two sub arrays A and B, then
I need to freshen up this documentation when I have the time. "Best cut" is too vague. The definition is really taken from the original paper. (MDLPC Criteron.)

2017-11-12 20:30 UTC, hlin117 requested changes
Can you break your PR into several parts? I would like to stop using the entire iris dataset as a unit test. Unit tests should be small, and easy to understand.

2017-11-12 21:26 UTC, dodgejoel commented
In response to your comments:
1. sounds good I will rework this to avoid using a dict. Your reasoning makes sense.
2. Sounds good. Following your suggestion I will make a smaller test data.
3. I think that breaking changes are different from just changes that alter behavior. It is true that someone performing discretization after this change would get a different result than what they get before this change but does that mean that it is a 'breaking' change? Adding a parameter to control whether or not every improvement will be used seems like a recipe for eventually overwhelming technical debt in this project - should it live so long and be so used :)

"Can you break your PR into several parts? I would like to stop using the entire iris dataset as a unit test. Unit tests should be small, and easy to understand."

Happy to do this. I will submit PRs to 1. modify the test suite as you suggest and then 2. update find_cut_points logic similar to what I have submitted in this PR. 

A question about github workflows: Once this branch has been developed to this point and submitted as a PR - what is the right way to refactor into multiple PRs? Do I manage separate local branches for each PR that I will submit and then submit them one at a time?  I am used to gerrit workflows so please excuse my ignorance here. Thanks!

2017-11-13 00:28 UTC, dodgejoel commented
Changes to test suite that you requested are in #29. I will plan on closing this pull request and pushing changes that you requested in separate pull requests that are curated a little more carefully to be modestly scoped and not bite off too many changes at once.

2017-11-21 05:31 UTC, closed without merging